# Introduction to PyTorch
## Basics of tensors, operations, 
## autograd, and a simple neural network

In [ ]:
import torch
print(torch.__version__)

2.9.1


In [13]:
# Creating tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2], [3, 4]])

print(a)
print(b)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [14]:
print(a.dtype)
print(b.shape)

torch.int64
torch.Size([2, 2])


In [15]:
#Tensor Initializations

zeros = torch.zeros(3, 3)
ones = torch.ones(2, 2)
random = torch.rand(2, 2)

print(zeros)
print(ones)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.2298, 0.9644],
        [0.8864, 0.7096]])


# Basic Tensor Operations

In [ ]:
x = torch.tensor([1.0, 2.0])
y = torch.tensor([3.0, 4.0])

print(x + y)
print(x * y)
print(torch.dot(x, y))


tensor([4., 6.])
tensor([3., 8.])
tensor(11.)


# NumPy ↔ PyTorch

In [17]:
import numpy as np

np_array = np.array([1, 2, 3])
torch_tensor = torch.from_numpy(np_array)

print(torch_tensor)


tensor([1, 2, 3])


In [18]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3*x + 1

y.backward()
print(x.grad)


tensor(7.)


# y = wx + b

In [ ]:

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

x = torch.tensor(2.0)
y = w*x + b

y.backward()

print(w.grad, b.grad)


tensor(2.) tensor(1.)


# Using torch.nn Module

In [21]:
import torch.nn as nn

model = nn.Linear(1, 1)
print(model)


Linear(in_features=1, out_features=1, bias=True)


# Forward Pass

In [22]:
x = torch.tensor([[2.0]])
y_pred = model(x)

print(y_pred)


tensor([[-1.8134]], grad_fn=<AddmmBackward0>)


# Loss Function

In [23]:
criterion = nn.MSELoss()

y_true = torch.tensor([[5.0]])
loss = criterion(y_pred, y_true)

print(loss)


tensor(46.4220, grad_fn=<MseLossBackward0>)


# Optimizer

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training Step

In [ ]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

print("Updated weights:", model.weight.data, model.bias.data)

Updated weights: tensor([[-0.2025]]) tensor([-0.7270])


# Mini Training Loop

In [ ]:
for epoch in range(5):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y_pred, y_true)
    loss.backward()
    optimizer.step()
    
    print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 37.6019
Epoch 1, Loss: 30.4575
Epoch 2, Loss: 24.6706
Epoch 3, Loss: 19.9832
Epoch 4, Loss: 16.1864


### What We Learned 
- Tensors in PyTorch
- Automatic differentiation
- Linear models
- Loss functions & optimizers
- Basic training loop